export class Cliente {
    idCliente: number
    idTipoDocumento: number
    nroDocumento: string
    nombres: string
    apellidos: string
    direccion: string
    distrito: string
    provincia: string
    sexo: string
    telefono: string
    email: string
    fechaNacimiento: string
    idEstadoCivil: number
    idPais: number
    ingresos: number
    lugarTrabajo: string
    ocupacion: string
    asesor: string
    conyuge: string
    tipoDocConyuge: number
    nroDocConyuge: string
    idEstadoCivilConyuge: number
    ocupacionConyuge: string
    tipoDocumento: any
    tipoDocumentoConyuge: any
    estadoCivil: any
    estadoCivilConyuge: any
}